
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kpszhcdmvqecmvbhmfbd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtwc3poY2RtdnFlY212YmhtZmJkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgyMTI1MjksImV4cCI6MjA2Mzc4ODUyOX0.TEIBNsPmDoKIeDXboUiOpHkxCwFhoir2dYFlg1zG7gY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// وظيفة لحذف جميع سجلات المدفوعات والأشهر المدفوعة
export const deleteAllPaymentsData = async () => {
  try {
    // حذف جميع سجلات الأشهر المدفوعة أولاً
    const { error: paidMonthsError } = await supabase
      .from('paid_months')
      .delete()
      .neq('id', '00000000-0000-0000-0000-000000000000');
      
    if (paidMonthsError) {
      console.error("خطأ في حذف الأشهر المدفوعة:", paidMonthsError);
      return { success: false, error: paidMonthsError };
    }
    
    // ثم حذف جميع سجلات المدفوعات
    const { error: paymentsError } = await supabase
      .from('payments')
      .delete()
      .neq('id', '00000000-0000-0000-0000-000000000000');
    
    if (paymentsError) {
      console.error("خطأ في حذف المدفوعات:", paymentsError);
      return { success: false, error: paymentsError };
    }
    
    return { success: true };
  } catch (error) {
    console.error("خطأ غير متوقع:", error);
    return { success: false, error };
  }
};
